name: Build on Self-Hosted EC2

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: self-hosted  # Make sure your EC2 runner is labeled 'self-hosted'

    steps:
    # Step 1: Checkout source code from repo
    - name: Checkout repository
      uses: actions/checkout@v4

    # Step 2: Set up Java JDK 21 using Temurin distribution
    - name: Set up Java 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'

    # Step 3: Check if Maven is installed, and install only if not present
    - name: Check and Install Maven if not present
      run: |
        if ! command -v mvn &> /dev/null; then
          echo "Maven not found, installing..."
          sudo apt update
          sudo apt install -y maven
        else
          echo "Maven is already installed"
          mvn -v
        fi

    # Step 4: Build project using Maven
    - name: Build with Maven
      run: mvn -B package --file pom.xml

    # Step 5: Run tests with Maven
    - name: Run Tests
      run: mvn test
